### ISSUE TITLE
Can you add coordinate change?

### ISSUE THREAD

**Issue by YunzeMan** [Obarads/vscode-pc-viewer#1]
This is a really handful extension in VSCode, thanks!

However, is it possible for you to add coordinate system change as a feature?
Some pcd files use a different XYZ system and with current viewer we can only rotate in a fixed XYZ coordinate and XY grid.

**Comment by Obarads** [comment]
Thanks for opening this issue!
I plan to add that feature, but it may take some time to implement.

**Comment by Obarads** [comment]
I add rotation and reverse features. The features are as follows. 
- `pcviewer.reverseCoordinate`: This feature flips objects(point cloud and axishelper) around an axis by changing values to true. This array order is [x, y, z].
- `pcviewer.rotateCoordinate`: This feature rotates objects  around an axis  by modifying values(degrees). This array order is [x, y, z].

**Comment by Obarads** [comment]
![ex0_origin](https://user-images.githubusercontent.com/13390730/85318760-833faa00-b4fb-11ea-9ce9-b1cf746a07ba.png)  
original data

![ex0_rotate_x-90](https://user-images.githubusercontent.com/13390730/85318832-9ce0f180-b4fb-11ea-8161-56726003b367.png)
I writed `"pcviewer.rotateCoordinate": [-90,0,0]` into setting.json.
